import { createApp } from 'vue';

// We disable eslint for the next line,
// Because assets are not versioned, and needs to be generated by yarn build:css
// eslint-disable-next-line
// import '@/assets/santefr/css/main.css';
// eslint-disable-next-line
// import '@/assets/sas/css/main-sas.css';

import App from '@/App.vue';

createApp(App);
